//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MorestachioMailProcessor.Services.TextService.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MorestachioMailProcessor.Services.TextService.Translations.UiTranslations", typeof(UiTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Application_Header_Close {
            get {
                return ResourceManager.GetString("Application.Header.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Application_Header_StartSend {
            get {
                return ResourceManager.GetString("Application.Header.StartSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Application_Header_Title {
            get {
                return ResourceManager.GetString("Application.Header.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Application_Navigation_Back {
            get {
                return ResourceManager.GetString("Application.Navigation.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Application_Navigation_Forward {
            get {
                return ResourceManager.GetString("Application.Navigation.Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Close_Description {
            get {
                return ResourceManager.GetString("Close.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Close_Title {
            get {
                return ResourceManager.GetString("Close.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataImport_PrepareStep_AddressPath {
            get {
                return ResourceManager.GetString("DataImport.PrepareStep.AddressPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataImport_PrepareStep_Errors_InvalidExpression {
            get {
                return ResourceManager.GetString("DataImport.PrepareStep.Errors.InvalidExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataImport_PrepareStep_Header_ExampleData {
            get {
                return ResourceManager.GetString("DataImport.PrepareStep.Header.ExampleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataImport_PrepareStep_Header_Expression {
            get {
                return ResourceManager.GetString("DataImport.PrepareStep.Header.Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataImport_PrepareStep_Header_Field {
            get {
                return ResourceManager.GetString("DataImport.PrepareStep.Header.Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataImport_PrepareStep_NamePath {
            get {
                return ResourceManager.GetString("DataImport.PrepareStep.NamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataImport_PrepareStep_SubjectPath {
            get {
                return ResourceManager.GetString("DataImport.PrepareStep.SubjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataImport_Selector_Description {
            get {
                return ResourceManager.GetString("DataImport.Selector.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataImport_Selector_SelectTitle {
            get {
                return ResourceManager.GetString("DataImport.Selector.SelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataImport_Selector_Title {
            get {
                return ResourceManager.GetString("DataImport.Selector.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataImport_Strategy_CSV_Description {
            get {
                return ResourceManager.GetString("DataImport.Strategy.CSV.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataImport_Strategy_CSV_Errors_InvalidFile {
            get {
                return ResourceManager.GetString("DataImport.Strategy.CSV.Errors.InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataImport_Strategy_CSV_Errors_InvalidPath {
            get {
                return ResourceManager.GetString("DataImport.Strategy.CSV.Errors.InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataImport_Strategy_CSV_FileName {
            get {
                return ResourceManager.GetString("DataImport.Strategy.CSV.FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataImport_Strategy_CSV_Name {
            get {
                return ResourceManager.GetString("DataImport.Strategy.CSV.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataImport_Strategy_CSV_Title {
            get {
                return ResourceManager.GetString("DataImport.Strategy.CSV.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MailDistributor_Prepare_Description {
            get {
                return ResourceManager.GetString("MailDistributor.Prepare.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MailDistributor_Prepare_Title {
            get {
                return ResourceManager.GetString("MailDistributor.Prepare.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MailDistributor_Selector_Description {
            get {
                return ResourceManager.GetString("MailDistributor.Selector.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MailDistributor_Selector_SelectTitle {
            get {
                return ResourceManager.GetString("MailDistributor.Selector.SelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MailDistributor_Selector_Title {
            get {
                return ResourceManager.GetString("MailDistributor.Selector.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MailDistributor_Strategy_ToDirectory_Description {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.ToDirectory.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MailDistributor_Strategy_ToDirectory_DirectoryPath {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.ToDirectory.DirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MailDistributor_Strategy_ToDirectory_Errors_InvalidDirectory {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.ToDirectory.Errors.InvalidDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MailDistributor_Strategy_ToDirectory_Name {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.ToDirectory.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MailDistributor_Strategy_ToDirectory_Title {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.ToDirectory.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Summery_Description {
            get {
                return ResourceManager.GetString("Summery.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Summery_Fields_GenerateAndSendParallel {
            get {
                return ResourceManager.GetString("Summery.Fields.GenerateAndSendParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Summery_Fields_ImportFrom {
            get {
                return ResourceManager.GetString("Summery.Fields.ImportFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Summery_Fields_SendVia {
            get {
                return ResourceManager.GetString("Summery.Fields.SendVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Summery_Fields_UseAddress {
            get {
                return ResourceManager.GetString("Summery.Fields.UseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Summery_Fields_UseName {
            get {
                return ResourceManager.GetString("Summery.Fields.UseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Summery_Title {
            get {
                return ResourceManager.GetString("Summery.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Template_Description {
            get {
                return ResourceManager.GetString("Template.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Template_Errors_InvalidTemplate {
            get {
                return ResourceManager.GetString("Template.Errors.InvalidTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Template_Title {
            get {
                return ResourceManager.GetString("Template.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Welcome_Content {
            get {
                return ResourceManager.GetString("Welcome.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Welcome_Title {
            get {
                return ResourceManager.GetString("Welcome.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WelcomeStep_Description {
            get {
                return ResourceManager.GetString("WelcomeStep.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WelcomeStep_Title {
            get {
                return ResourceManager.GetString("WelcomeStep.Title", resourceCulture);
            }
        }
    }
}
