//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morestachio.MailProcessor.Ui.Services.TextService.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Morestachio.MailProcessor.Ui.Services.TextService.Translations.UiTranslations", typeof(UiTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_ConfirmQuestion_Title {
            get {
                return ResourceManager.GetString("Application.ConfirmQuestion.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_Error_Title {
            get {
                return ResourceManager.GetString("Application.Error.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_FeatureUnsupported_Message {
            get {
                return ResourceManager.GetString("Application.FeatureUnsupported.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_FeatureUnsupported_Title {
            get {
                return ResourceManager.GetString("Application.FeatureUnsupported.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_Header_Close {
            get {
                return ResourceManager.GetString("Application.Header.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_Header_StartSend {
            get {
                return ResourceManager.GetString("Application.Header.StartSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_Header_Title {
            get {
                return ResourceManager.GetString("Application.Header.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_LoadSettings_Error_Message {
            get {
                return ResourceManager.GetString("Application.LoadSettings.Error.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_LoadSettings_Error_Title {
            get {
                return ResourceManager.GetString("Application.LoadSettings.Error.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_Navigation_Back {
            get {
                return ResourceManager.GetString("Application.Navigation.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_Navigation_Close_Message {
            get {
                return ResourceManager.GetString("Application.Navigation.Close.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_Navigation_Close_Title {
            get {
                return ResourceManager.GetString("Application.Navigation.Close.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_Navigation_Forward {
            get {
                return ResourceManager.GetString("Application.Navigation.Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_Save_Title {
            get {
                return ResourceManager.GetString("Application.Save.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_Storage_Filename_Message {
            get {
                return ResourceManager.GetString("Application.Storage.Filename.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_Storage_Filename_Title {
            get {
                return ResourceManager.GetString("Application.Storage.Filename.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_Storage_OverwriteExisting_Message {
            get {
                return ResourceManager.GetString("Application.Storage.OverwriteExisting.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Application_Storage_OverwriteExisting_Title {
            get {
                return ResourceManager.GetString("Application.Storage.OverwriteExisting.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Close_Description {
            get {
                return ResourceManager.GetString("Close.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Close_Title {
            get {
                return ResourceManager.GetString("Close.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CloseStep_Content {
            get {
                return ResourceManager.GetString("CloseStep.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CloseStep_Title {
            get {
                return ResourceManager.GetString("CloseStep.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_PrepareStep_AddressPath {
            get {
                return ResourceManager.GetString("DataImport.PrepareStep.AddressPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_PrepareStep_Errors_InvalidAddress {
            get {
                return ResourceManager.GetString("DataImport.PrepareStep.Errors.InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_PrepareStep_Errors_InvalidExpression {
            get {
                return ResourceManager.GetString("DataImport.PrepareStep.Errors.InvalidExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_PrepareStep_FromAddressPath {
            get {
                return ResourceManager.GetString("DataImport.PrepareStep.FromAddressPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_PrepareStep_FromNamePath {
            get {
                return ResourceManager.GetString("DataImport.PrepareStep.FromNamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_PrepareStep_Header_ExampleData {
            get {
                return ResourceManager.GetString("DataImport.PrepareStep.Header.ExampleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_PrepareStep_Header_Expression {
            get {
                return ResourceManager.GetString("DataImport.PrepareStep.Header.Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_PrepareStep_Header_Field {
            get {
                return ResourceManager.GetString("DataImport.PrepareStep.Header.Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_PrepareStep_NamePath {
            get {
                return ResourceManager.GetString("DataImport.PrepareStep.NamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_PrepareStep_SubjectPath {
            get {
                return ResourceManager.GetString("DataImport.PrepareStep.SubjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_Selector_Description {
            get {
                return ResourceManager.GetString("DataImport.Selector.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_Selector_SelectTitle {
            get {
                return ResourceManager.GetString("DataImport.Selector.SelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_Selector_Title {
            get {
                return ResourceManager.GetString("DataImport.Selector.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_Strategy_CSV_Description {
            get {
                return ResourceManager.GetString("DataImport.Strategy.CSV.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_Strategy_CSV_Errors_InvalidFile {
            get {
                return ResourceManager.GetString("DataImport.Strategy.CSV.Errors.InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_Strategy_CSV_Name {
            get {
                return ResourceManager.GetString("DataImport.Strategy.CSV.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_Strategy_CSV_Title {
            get {
                return ResourceManager.GetString("DataImport.Strategy.CSV.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_Strategy_Errors_InvalidPath {
            get {
                return ResourceManager.GetString("DataImport.Strategy.Errors.InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_Strategy_FileName {
            get {
                return ResourceManager.GetString("DataImport.Strategy.FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_Strategy_Json_Description {
            get {
                return ResourceManager.GetString("DataImport.Strategy.Json.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_Strategy_Json_Name {
            get {
                return ResourceManager.GetString("DataImport.Strategy.Json.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_Strategy_Json_Title {
            get {
                return ResourceManager.GetString("DataImport.Strategy.Json.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_Strategy_Sql_Description {
            get {
                return ResourceManager.GetString("DataImport.Strategy.Sql.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_Strategy_Sql_Errors_NoConnectionString {
            get {
                return ResourceManager.GetString("DataImport.Strategy.Sql.Errors.NoConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_Strategy_Sql_Errors_NoQuery {
            get {
                return ResourceManager.GetString("DataImport.Strategy.Sql.Errors.NoQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_Strategy_Sql_Fields_ConnectionString {
            get {
                return ResourceManager.GetString("DataImport.Strategy.Sql.Fields.ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_Strategy_Sql_Fields_Query {
            get {
                return ResourceManager.GetString("DataImport.Strategy.Sql.Fields.Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_Strategy_Sql_Name {
            get {
                return ResourceManager.GetString("DataImport.Strategy.Sql.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataImport_Strategy_Sql_Title {
            get {
                return ResourceManager.GetString("DataImport.Strategy.Sql.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Help_Title {
            get {
                return ResourceManager.GetString("Help.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ImportData_Errors_Validate_Description {
            get {
                return ResourceManager.GetString("ImportData.Errors.Validate.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ImportData_Errors_Validate_GeneralError {
            get {
                return ResourceManager.GetString("ImportData.Errors.Validate.GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ImportData_Errors_Validate_Title {
            get {
                return ResourceManager.GetString("ImportData.Errors.Validate.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Prepare_Description {
            get {
                return ResourceManager.GetString("MailDistributor.Prepare.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Prepare_Title {
            get {
                return ResourceManager.GetString("MailDistributor.Prepare.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Selector_Description {
            get {
                return ResourceManager.GetString("MailDistributor.Selector.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Selector_SelectTitle {
            get {
                return ResourceManager.GetString("MailDistributor.Selector.SelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Selector_Title {
            get {
                return ResourceManager.GetString("MailDistributor.Selector.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Strategy_Smtp_Description {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.Smtp.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Strategy_Smtp_Errors_InvalidHost {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.Smtp.Errors.InvalidHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Strategy_Smtp_Errors_InvalidPort {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.Smtp.Errors.InvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Strategy_Smtp_Errors_NoHost {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.Smtp.Errors.NoHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Strategy_Smtp_Errors_NoPassword {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.Smtp.Errors.NoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Strategy_Smtp_Errors_NoUsername {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.Smtp.Errors.NoUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Strategy_Smtp_Fields_Host {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.Smtp.Fields.Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Strategy_Smtp_Fields_Password {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.Smtp.Fields.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Strategy_Smtp_Fields_Port {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.Smtp.Fields.Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Strategy_Smtp_Fields_Username {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.Smtp.Fields.Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Strategy_Smtp_Fields_ValidationResult {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.Smtp.Fields.ValidationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Strategy_Smtp_Name {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.Smtp.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Strategy_Smtp_Save_EncryptPassword_Message {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.Smtp.Save.EncryptPassword.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Strategy_Smtp_Save_EncryptPassword_Title {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.Smtp.Save.EncryptPassword.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Strategy_Smtp_Title {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.Smtp.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Strategy_ToDirectory_Description {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.ToDirectory.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Strategy_ToDirectory_DirectoryPath {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.ToDirectory.DirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Strategy_ToDirectory_Errors_InvalidDirectory {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.ToDirectory.Errors.InvalidDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Strategy_ToDirectory_Name {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.ToDirectory.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MailDistributor_Strategy_ToDirectory_Title {
            get {
                return ResourceManager.GetString("MailDistributor.Strategy.ToDirectory.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SaveReport_Description {
            get {
                return ResourceManager.GetString("SaveReport.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SaveReport_Title {
            get {
                return ResourceManager.GetString("SaveReport.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SendReport_Refresh_Title {
            get {
                return ResourceManager.GetString("SendReport.Refresh.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SendReport_Save_Title {
            get {
                return ResourceManager.GetString("SendReport.Save.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Structure_Display_Name {
            get {
                return ResourceManager.GetString("Structure.Display.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Structure_Display_Type {
            get {
                return ResourceManager.GetString("Structure.Display.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Summery_Commands_Report {
            get {
                return ResourceManager.GetString("Summery.Commands.Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Summery_Commands_Reset {
            get {
                return ResourceManager.GetString("Summery.Commands.Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Summery_Description {
            get {
                return ResourceManager.GetString("Summery.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Summery_Error_Message {
            get {
                return ResourceManager.GetString("Summery.Error.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Summery_Fields_GenerateAndSendParallel {
            get {
                return ResourceManager.GetString("Summery.Fields.GenerateAndSendParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Summery_Fields_ImportFrom {
            get {
                return ResourceManager.GetString("Summery.Fields.ImportFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Summery_Fields_NoOfParallism {
            get {
                return ResourceManager.GetString("Summery.Fields.NoOfParallism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Summery_Fields_ParallelReadAheadCount {
            get {
                return ResourceManager.GetString("Summery.Fields.ParallelReadAheadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Summery_Fields_Progress {
            get {
                return ResourceManager.GetString("Summery.Fields.Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Summery_Fields_Progress_Failed {
            get {
                return ResourceManager.GetString("Summery.Fields.Progress.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Summery_Fields_Progress_ProcessedNumber {
            get {
                return ResourceManager.GetString("Summery.Fields.Progress.ProcessedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Summery_Fields_Progress_Success {
            get {
                return ResourceManager.GetString("Summery.Fields.Progress.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Summery_Fields_SendVia {
            get {
                return ResourceManager.GetString("Summery.Fields.SendVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Summery_Fields_UseAddress {
            get {
                return ResourceManager.GetString("Summery.Fields.UseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Summery_Fields_UseName {
            get {
                return ResourceManager.GetString("Summery.Fields.UseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Summery_Fields_UseSubject {
            get {
                return ResourceManager.GetString("Summery.Fields.UseSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Summery_Progress_ObtainTemplate_Message {
            get {
                return ResourceManager.GetString("Summery.Progress.ObtainTemplate.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Summery_Progress_ObtainTemplate_Title {
            get {
                return ResourceManager.GetString("Summery.Progress.ObtainTemplate.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Summery_Result_Title {
            get {
                return ResourceManager.GetString("Summery.Result.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Summery_Template_Confirm_Message {
            get {
                return ResourceManager.GetString("Summery.Template.Confirm.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Summery_Title {
            get {
                return ResourceManager.GetString("Summery.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Template_Description {
            get {
                return ResourceManager.GetString("Template.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Template_Errors_InvalidTemplate {
            get {
                return ResourceManager.GetString("Template.Errors.InvalidTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Template_Errors_LoadTemplate {
            get {
                return ResourceManager.GetString("Template.Errors.LoadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Template_Preview_Title {
            get {
                return ResourceManager.GetString("Template.Preview.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Template_PreviewWindow_Html_Title {
            get {
                return ResourceManager.GetString("Template.PreviewWindow.Html.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Template_PreviewWindow_Html_Warning {
            get {
                return ResourceManager.GetString("Template.PreviewWindow.Html.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Template_PreviewWindow_Plain_Title {
            get {
                return ResourceManager.GetString("Template.PreviewWindow.Plain.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Template_PreviewWindow_Title {
            get {
                return ResourceManager.GetString("Template.PreviewWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Template_Title {
            get {
                return ResourceManager.GetString("Template.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Validate_Progress_Message {
            get {
                return ResourceManager.GetString("Validate.Progress.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Validate_Progress_Title {
            get {
                return ResourceManager.GetString("Validate.Progress.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Validate_Title {
            get {
                return ResourceManager.GetString("Validate.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Welcome_Content {
            get {
                return ResourceManager.GetString("Welcome.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Welcome_InstallWebViewer {
            get {
                return ResourceManager.GetString("Welcome.InstallWebViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Welcome_Savefiles {
            get {
                return ResourceManager.GetString("Welcome.Savefiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Welcome_Title {
            get {
                return ResourceManager.GetString("Welcome.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Welcome_WebViewerInstalled_Title {
            get {
                return ResourceManager.GetString("Welcome.WebViewerInstalled.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Welcome_WebViewerNotInstalled_Title {
            get {
                return ResourceManager.GetString("Welcome.WebViewerNotInstalled.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WelcomeStep_Description {
            get {
                return ResourceManager.GetString("WelcomeStep.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WelcomeStep_Title {
            get {
                return ResourceManager.GetString("WelcomeStep.Title", resourceCulture);
            }
        }
    }
}
